### ISSUE TITLE
Old version of embedded Chrome

### ISSUE THREAD

**Issue by jakubjosef** [rogargon/angular-e2e#1]
Hi, can you create new version with latest chrome?

```
webpack: Compiled successfully.
[11:54:01] I/file_manager - creating folder /home/jenkins/workspace/dev-test/node_modules/webdriver-manager/selenium
[11:54:02] I/update - chromedriver: unzipping chromedriver_2.38.zip
[11:54:02] I/update - chromedriver: setting permissions to 0755 for /home/jenkins/workspace/dev-test/node_modules/webdriver-manager/selenium/chromedriver_2.38
[11:54:02] I/launcher - Running 1 instances of WebDriver
[11:54:02] I/direct - Using ChromeDriver directly...
[11:54:04] E/launcher - session not created exception: Chrome version must be >= 65.0.3325.0
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.13.0-1011-azure x86_64)
[11:54:04] E/launcher - SessionNotCreatedError: session not created exception: Chrome version must be >= 65.0.3325.0
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.13.0-1011-azure x86_64)
    at Object.checkLegacyResponse (/home/jenkins/workspace/dev-test/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/home/jenkins/workspace/dev-test/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/home/jenkins/workspace/dev-test/node_modules/selenium-webdriver/lib/http.js:440:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/home/jenkins/workspace/dev-test/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at Function.createSession (/home/jenkins/workspace/dev-test/node_modules/selenium-webdriver/chrome.js:709:29)
    at Direct.getNewDriver (/home/jenkins/workspace/dev-test/node_modules/protractor/lib/driverProviders/direct.ts:90:25)
    at Runner.createBrowser (/home/jenkins/workspace/dev-test/node_modules/protractor/lib/runner.ts:225:39)
    at q.then.then (/home/jenkins/workspace/dev-test/node_modules/protractor/lib/runner.ts:391:27)
    at _fulfilled (/home/jenkins/workspace/dev-test/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/jenkins/workspace/dev-test/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/jenkins/workspace/dev-test/node_modules/q/q.js:796:13)
    at /home/jenkins/workspace/dev-test/node_modules/q/q.js:556:49
    at runSingle (/home/jenkins/workspace/dev-test/node_modules/q/q.js:137:13)
    at flush (/home/jenkins/workspace/dev-test/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[11:54:04] E/launcher - Process exited with error code 199
error Command failed with exit code 199.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by rogargon** [comment]
Rebuild it and now includes Google Chrome 66.0.3359.139 in "latest". 
Please, let me know if this solves your issue

**Comment by jakubjosef** [comment]
Sorry I little forgot to this issue, but yes - now i don't have to call `apt-get install -y google-chrome-stable` in my CI/CD test pipeline. 
I'm gonna close this issue. Thx for quick response.

P.S.: I still have to install libgconf-2-4 pkg to have working tests.
